version: "3.7"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-public

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - traefik-public

  n8n:
    image: n8nio/n8n:latest
    depends_on:
      - postgres
      - redis
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: secure_password

      GENERIC_TIMEZONE: "Asia/Kolkata"
      N8N_HOST: ${DOMAIN}
      N8N_PROTOCOL: https
      N8N_PORT: 5678
      N8N_LISTEN_ADDRESS: 0.0.0.0
      WEBHOOK_URL: https://${DOMAIN}
      N8N_EDITOR_BASE_URL: https://${DOMAIN}
      N8N_PROXY_HOPS: 1

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "sdfsdfsd64564gffgvccvbcvbcvczxc"
      N8N_USER_MANAGEMENT_DISABLED: "false"
      N8N_RUNNERS_ENABLED: "true"
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

      NODE_FUNCTION_ALLOW_EXTERNAL: "*"
      NODE_FUNCTION_ALLOW_BUILTIN: "*"
    volumes:
      - n8n_data:/home/node/.n8n
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.n8n.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.n8n.entrypoints=https
        - traefik.http.routers.n8n.tls=true
        - traefik.http.routers.n8n.tls.certresolver=le
        - traefik.http.services.n8n.loadbalancer.server.port=5678
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
    networks:
      - traefik-public

  n8n_worker:
    image: n8nio/n8n:latest
    depends_on:
      - postgres
      - redis
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: secure_password

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "sdfsdfsd64564gffgvccvbcvbcvczxc"
      N8N_PROTOCOL: https
      N8N_RUNNERS_ENABLED: "true"
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

      NODE_FUNCTION_ALLOW_EXTERNAL: "*"
      NODE_FUNCTION_ALLOW_BUILTIN: "*"
    volumes:
      - n8n_data:/home/node/.n8n
    command: worker
    networks:
      - traefik-public

volumes:
  postgres_data:
  redis_data:
  n8n_data:

networks:
  traefik-public:
    external: true
