version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: n8n_postgres
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  redis:
    image: redis:7
    restart: always
    container_name: n8n_redis
    networks:
      - n8n_network
    volumes:
      - redis_data:/data

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    container_name: n8n
    depends_on:
      - postgres
      - redis
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: secure_password
      GENERIC_TIMEZONE: "UTC"

      # Correct public URL and protocol for webhook registration
      N8N_HOST: ai-n8n.bloomi5.com
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://ai-n8n.bloomi5.com/

      # Queue mode with Redis
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379

      N8N_ENCRYPTION_KEY: "sdfsdfsd64564gffgvccvbcvbcvczxc"

      # Enable User Management Without SMTP
      N8N_USER_MANAGEMENT_DISABLED: "false"

      N8N_RUNNERS_ENABLED: true
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true

    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

  n8n_worker:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    container_name: n8n_worker
    depends_on:
      - postgres
      - redis
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: secure_password
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      N8N_ENCRYPTION_KEY: "sdfsdfsd64564gffgvccvbcvbcvczxc"
      N8N_PROTOCOL: https
      N8N_RUNNERS_ENABLED: true
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
    command: worker

  nginx:
    image: nginx:latest
    restart: always
    container_name: n8n_nginx
    depends_on:
      - n8n
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  postgres_data:
  n8n_data:
  redis_data:
